spring:
  application:
    name: spring-redis-example

#  redis:
#    host: localhost
#    port: 6379

  cache:
    type: redis

logging:
  level:
    com.example.demo.service: DEBUG
    org.springframework.data.redis: INFO

server:
  port: 8080
